import "bootstrap/dist/css/bootstrap.min.css";
import './styles/style.scss'
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: 'Welcome to private-access',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" />
      </head>
      <body suppressHydrationWarning={true} className="home darkGreen" >
        <Header />
        {children}
        <Footer />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js" async></script>
      </body>
    </html>
  );
}
